[package]
name    = "fractal-shard"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
solana-sdk = { workspace = true }
dashmap    = { workspace = true }
lazy_static= { workspace = true }
